### PR TITLE
fixes to Debian package

### PR DESCRIPTION
**Pull request by david415**
here in this pull request i've merged in the latest develop branch which contains some changes such as moving aside unused filter policy files and corrections to the gnome extension and oz-daemon filter policies.

### CODE REVIEW

**Comment by david415** [comment]
we probably have to rerun godeps to rebuild the dependencies since roflcoptor now depends on the procsnitchd/service golang module.

**Comment by dma** [comment]
I wasn't sure about what you wanted to do with the unused filter files. 

re: allowing progress notices to Gnome Shell, any reason it's not ".. PROGRESS=\d+ "?

**Comment by david415** [comment]
yeah... after the PROGRESS tor sometimes given a description which can be different depending on how many relays the circuit is currently built thru

**Comment by david415** [comment]
oh but i guess it should be PROGRESS=\d+.+ or something like that

**Comment by david415** [comment]
or we could just use a string prefix match

**Comment by david415** [comment]
closing for now

**Pull request closed without merging**
